### ISSUE TITLE
Update for line width

### ISSUE THREAD

**Issue by ayunami2000** [maltaisn/svg-equations#2]
now that desmos supports modifying line widths, is it possible to create console code that adds items to the graph with things like colors, line width, and opacity set?

**Comment by maltaisn** [comment]
I've never really used the console codes, are they documented somewhere? If you know about them, perhaps you could make a prototype and send a pull request.

**Comment by ayunami2000** [comment]
If you open the developer console in Desmos you can edit values like so:

```
var tmpState=Calc.getState();
//try adding items to the expression list to see how they are structured. Their data will appear in the array `tmpState.expressions.list`
console.log(tmpState.expressions.list);
//edit values in the array to make changes. Your program could generate javascript that sets these values. Example if the first item in your graph's expression list is a point, function, or polygon(...):
tmpState.expressions.list[0].color="#FFFF00";
Calc.setState(tmpState);
```

Desmos also supports gradients now* as well as color in the form of variables (opacity and line width/point size are also variable controllable)

To set colors with variables or directly, use the `tmpState.expressions.list[...].colorLatex` property

*gradients only seem to work on lists of points but not on the lines when you choose to show lines connecting points

***also I suggest that you make it store the expression data in a folder. Expressions are set to be stored in a folder via "folderId" which matches the "id" property of the folder item

Edit: I completely forgot: tables can be very helpful as well especially for mass storage of data

**Comment by TrimanSingh** [comment]
@maltaisn 
I am using you script to generate graphs of portraits. The tool is great but the absence of color is sad.

I have learned that the tool, plots the equation in order that they were sketched in the vector program. For coloring the lines i use a short javascript to color the equations.

```
var urlArray = window.location.pathname.split('/');          //splits the url path after '.com/' into an array
var url = window.location.hostname + "/" + urlArray[1]       //stores www.desmos.com/calculator in var 'url'
if (url == "www.desmos.com/calculator")                      //check for if the website is desmos
{
	state = Calc.getState();                                 //desmos api to get state
															 
	var i;                                                    
															  
	var min = prompt("minimum number");                      //to get the start point of eq to color 
	var max = prompt("maximum number");                      //to get the end point of eq to color 
	var color = prompt ("color");                            //to get the the hex code of color 
															  
	for (i = min-1; i < max; i++)                            //loop to color the eq from min to max
	{                                                         
		state.expressions.list[i].color = "#"+color;          
	}                                                         
															  
	Calc.setState(state);                                    //desmos api to save the state  
}                                                             
															  
else                                                         //if website is not desmos 
{                                                            
	alert("This does not seem to be desmos!");               //check for if the website is desmos
}               
```

If you could get a way to get the stroke color of svg elements you could plot graph with coloured lines 

```
state = Calc.getState();
state.expressions.list[0].color = "hexcode of color of eq1";
state.expressions.list[1].color = "hexcode of color of eq2";
state.expressions.list[2].color = "hexcode of color of eq3";
Calc.setState(state);       
```   

I can't submit a pull request i don't even know a little bit of java          
PS-Sorry to disturb you

**Comment by ayunami2000** [comment]
@MrMatrix1729 so in browsers you can use `getComputedStyle` so perhaps you can try to get the color from that? the only issue is if there are also [CSS filters](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/invert()) applied which can break that....

**Comment by maltaisn** [comment]
I'll see what I can do next week.

**Comment by TrimanSingh** [comment]
@ayunami2000 I was not trying to say that

I was saying- In vector graphics there are two properties **Fill and stroke**. Though the tool uses path for converting it to equations, in **most cases** the path is the same as stroke(stroke can also be 0). 

What the tool should do(just a opinion)- It should get all the stroke colors as hex code and store it in a javascript file in format
```
state = Calc.getState();
state.expressions.list[0].color = "hexcode of eq1";
state.expressions.list[1].color = "hexcode of eq2";
state.expressions.list[2].color = "hexcode of eq3";
Calc.setState(state);     
```

After that the user could copy all the content of equation file (.txt) and graph it in desmos, then he/she will copy content of JS file and paste it in the console of the desmos graph. 

This will color the lines of almost all the equation in desmos and will not take into account fill(in vector graphic) to fill color in graph in desmos.

**Comment by maltaisn** [comment]
I just release v1.1.0, with support for 3 additional path attributes: `stroke` (for color), `stroke-width` (for line width) and `stroke-opacity`/`opacity`. There's a new CLI option `-s` to generate a JavaScript file which can be copy-pasted to the console to set the styling attributes on the equations. Make sure to reread the readme, there's a few quirks concerning the line width.
