### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by charlie32768** [maltaisn/svg-equations#4]
sorry if this is a really really dumb question im brand new to this github thing but the problem im having is that anytime i try to run the jar file through the terminal it just says "unable to access jarfile svgeq.jar" im using an m1 macbook air if that matters

**Comment by TrimanSingh** [comment]
Make sure that jar file is there in the directory where your terminal is pointing to

**Comment by charlie32768** [comment]
it worked! here is the result https://www.desmos.com/calculator/jzns00zo4t
