### ISSUE TITLE
Downloaded, the zip file and the svgeq-release.jar but didn't work

### ISSUE THREAD

**Issue by ashahin96** [maltaisn/svg-equations#5]
i tried the :
java -jar "C:/path-to-jar/svgeq-release.jar" <mySvgFileName.svg> -e parametric --latex **: Failder**

java -jar "C:/path-to-jar/svgeq-release.jar" <mySvgFileName.svg> --latex   **: Failder**

java -jar "C:/path-to-jar/svgeq-release.jar" <mySvgFileName.svg> [-e parametric --latex] : **Failder**

java -jar "C:/path-to-jar/svgeq-release.jar" <mySvgFileName.svg> [ --latex] **: Failder**

java -jar "C:/path-to-jar/svgeq-release.jar" <mySvgFileName.svg> [-p 3 -e parametric --latex --lenient] **: Failder**

java -jar "C:/path-to-jar/svgeq-release.jar" <mySvgFileName.svg> [-p  -e parametric --latex --lenient] **: Failder**

java -jar "C:/path-to-jar/svgeq-release.jar" <mySvgFileName.svg> [-p  -e parametric --latex --lenient] **: Failder**

java -jar "C:/path-to-jar/svgeq-release.jar" <"C:/path-to-svg/mySvgFileName.svg"> [-p  -e parametric --latex --lenient] **: Failder**

**-what i get back is a file named either "-e","-e","--latex" contains: "ERROR: SVG parsing error: Input file doesn't exist." or "ERROR: Unknown option: --latex]"
 **

I'm sure the program works since other users generated equations from it but this is what's happing with me; 

![Screenshot 2021-03-22 123750](https://user-images.githubusercontent.com/64437375/111977477-717f4780-8b0b-11eb-8dba-890eaf898824.png)

**Comment by maltaisn** [comment]
It seems you're using all kinds of symbols that aren't needed (`<`, `>`, `[`) etc.   
`>` will write to a file, which explains why you're getting a `-e` file. Get rid of the symbols.
```
java -jar "C:/path-to-jar/svgeq-release.jar" "C:/path-to-svg/mySvgFileName.svg" -p -e parametric --latex --lenient
```

**Comment by ashahin96** [comment]
thank you i did what you said and it worked , God bless
