### ISSUE TITLE
Image gets flipped when processed

### ISSUE THREAD

**Issue by bababooey1234** [maltaisn/svg-equations#6]
I'm using this SVG image of sans (github won't let me upload), generated by OpenCV and Potrace. When I view it in a browser or rasterise it in photoshop, it is right side up, but when I convert it using svgeq and put the equations generated into desmos using javascript, it appears upside down. 

I've tried using --transform="translate(-1,1)" and (1,1), but neither did anything.

Running with the command java -jar svgeq-release.jar C:\Users\papyr\Desktop\Programming\miscelleneous\traced\traced0001.svg --transform="translate(-1,1)"

Output:
[traced0001-output.txt](https://github.com/maltaisn/svg-equations/files/6444687/traced0001-output.txt)

![image](https://user-images.githubusercontent.com/82023869/117516358-3ca45280-afdc-11eb-9de6-bd31b15fdb80.png)

![image](https://user-images.githubusercontent.com/82023869/117516440-72493b80-afdc-11eb-9e11-6b47d1868464.png)

**Comment by maltaisn** [comment]
You can put the SVG on github by putting it in a zip archive. My guess is there's already a transform in your image that the tool doesn't pick up, so the image appears flipped. You can invert the Y axis by using `--transform="scale(1 -1)"`.

**Comment by bababooey1234** [comment]
Thanks, thought you had to do scale(1,-1) not scale(1 -1). It's now working as it should.
