### ISSUE TITLE
Empty output

### ISSUE THREAD

**Issue by MoaazHudhud** [maltaisn/svg-equations#8]
hey guys,

I have been trying to use the program and it worked well but when I tried to use it with mine it didn't work. do you know why?

[here](https://www.dropbox.com/t/Iz62XrJhAtO7oTfK)

here as a png:
![terminal](https://user-images.githubusercontent.com/82755353/120076284-7fbe8680-c0ad-11eb-8028-23fea5b8f8d6.png)

**Comment by maltaisn** [comment]
Your SVG has a single element, which is an embedded base64-encoded raster image. Raster images are not vector graphics, thus aren't supported. Consider using another image, or using a tool like Inkscape to trace the bitmap (i.e. converting it to a path).
