### ISSUE TITLE
Having trouble compiling to jar

### ISSUE THREAD

**Issue by hairbear** [maltaisn/svg-equations#9]
Sorry if this question is elementary, I'm completely new to Java development! 
I'm trying to modify this project to add separators between the different SVG paths, which seems to be simple enough, but from there I can't figure out how to compile the code to a jar file. Leaving the ```build.gradle.kts``` as is compiles only to an app.jar without a main manifest attribute, and when I try to modify it I invariably get the error ```Caused by: java.lang.ClassNotFoundException: com.maltaisn.svgequations.MainKt```. Any help would be greatly appreciated.

**Comment by maltaisn** [comment]
It should be as simple as running:
```
./gradlew clean build dist
```
The `dist` task is what builds the jar file. You can leave out the last line `finalizedBy(tasks.named("shrinkJar"))` if you're having trouble with ProGuard. The jar file will  be located in `app/build/libs/svgeq.jar`.

**Comment by hairbear** [comment]
Thanks, that worked perfectly! Didn't realize ```dist``` was necessary and yeah it was necessary to leave out the last line.
